[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta:__legacy__"

[project]
name = "arglite"
version = "0.30.5"
requires-python = ">=3.10"
dependencies = [
    "rich",
    "pyyaml",
    "jsonschema",
]
authors = [
    {name = "Douglas Luman", email = "dluman@allegheny.edu"}
]
readme = "README.md"
description = "A lightweight, explicit arg parser for fun, but not profit."

[project.optional-dependencies]
dev = [
    "pytest",
    "twine",
]
docs = [
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings[python]",
]

[tool.setuptools.package-data]
arglite = ["schema.json"]
