name: CI

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  check-upstream:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.0
      with:
        fetch-depth: '0'
    - name: vurze check
      run: |
        python -m pip install vurze
        vurze check src/arglite/arglite.py
        vurze check src/arglite/code.py
        vurse check src/arglite/arguments.py
